### ISSUE TITLE
AwesomeCV Reduce Margins

### ISSUE THREAD

**Issue by hank-w** [posquit0/ama#10]
Hello Byungjin, thank you very much for the awesome template! I was wondering do you know how to reduce the space between sections subsections? I want to reduce the margins between Skills and the skills table. I also want to reduce the space between the Job title and job position, Thanks!

**Comment by posquit0** [comment]
Hi,
Thank you for using AwesomeCV. I haven't touched that project for a long time so I can't help.

Please post your issue with details on [Awesome-CV GitHub issues](https://github.com/posquit0/Awesome-CV/issues). Then, you can get help from people. 

This is a place to post personal questions. 😄
