### ISSUE TITLE
안녕하세요. 패캠 강좌 듣는 학생입니다. 질문이 있습니다!

### ISSUE THREAD

**Issue by Saulabi** [posquit0/ama#15]
AWS CLI 강좌에서 nvim을 통해 aws/config 파일이 수정이 되지 않습니다.
E212: Can't open file for writing: no such file or directory
이 에러문구가 뜨고 검색을 통해서
w !sudo tee % 도 해보았고 
sudo nvim으로도 열어보았지만 해결이 되지 않았습니다.

**Comment by posquit0** [comment]
강의 질문은 https://github.com/tedilabs/fastcampus-devops/discussions 이용 부탁드립니다!
AWS CLI의 인증 설정정보는 `~/.aws/config`에 저장됩니다. 디렉토리가 존재하는지 확인 후에 존재하지 않는다면 `mkdir ~/.aws` 명령어로 디렉토리를 생성 후에 본인이 선호하는 에디터로 `~/.aws/config` 파일을 작성하시면 됩니다.
