### ISSUE TITLE
Help! :(  [didn't know how to add an emoji]

### ISSUE THREAD

**Issue by Eyituoyo** [posquit0/ama#21]
Thanks for the awesome cv template! It is really helpful

I would like to do something a little different for the skills section, would you be able to assist me with this. I've been struggling for the past week 

See below images

![image](https://user-images.githubusercontent.com/99544386/153714938-145a9ab8-24d6-4a53-b274-9d1d48cbd100.png)

But I would like to achieve this image ( see below)

![image](https://user-images.githubusercontent.com/99544386/153714955-e9380972-9d90-4e2b-b8ff-57650a5397db.png)

Would really appreciate if you could get back to me and I could share the file with you,

**Comment by posquit0** [comment]
Hi,
Thank you for using AwesomeCV. I haven't touched that project for a long time so I can't help.

Please post your issue with details on [Awesome-CV GitHub issues](https://github.com/posquit0/Awesome-CV/issues). Then, you can get help from people. 

This is a place to post personal questions. 😄
