### ISSUE TITLE
Awesome CV installation

### ISSUE THREAD

**Issue by SimonPaul02** [posquit0/ama#24]
Hi,

I have some problems installing your cv on my local machine (windows). https://github.com/posquit0/Awesome-CV
I installed TexMaker and TexWorks but it doesn't work with both editors: This is XeTeX, Version 3.141592653-2.6-0.999994 (MiKTeX 22.3) (preloaded format=xelatex.fmt)
 restricted \write18 enabled.
entering extended mode
(resume.tex
LaTeX2e <2021-11-15> patch level 1
L3 programming layer <2022-02-24> (awesome-cv.cls

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 .
     ./awesome-cv.cls
? 

 I can't run $ xelatex {your-cv}.tex at the command prompt.
(At the master folder). 
Could you help me out?

Thank you!

**Comment by posquit0** [comment]
Hi,
Thank you for using AwesomeCV. I haven't touched that project for a long time so I can't help.

Please post your issue with details on [Awesome-CV GitHub issues](https://github.com/posquit0/Awesome-CV/issues). Then, you can get help from people. 

This is a place to post personal questions. 😄
