### ISSUE TITLE
How to align Skills to the Left for Awesome-CV resume template

### ISSUE THREAD

**Issue by throwAway1023** [posquit0/ama#3]
Hey, I'm having a hard time aligning the skills to the left. I've been trying for a long time but I'm new to Latex, can you please help me out? :(

Issue (current state):
![Capture](https://user-images.githubusercontent.com/49723752/56295193-6428d980-60fa-11e9-8e97-3bd8b0f0b966.PNG)

Desired:
![Capture10](https://user-images.githubusercontent.com/49723752/56295205-6854f700-60fa-11e9-8722-ef608af40cb1.PNG)

This is the code for the /cvskills:
% Define an environment for cvskill
\newenvironment{cvskills}{
  \begin{center}
    \setlength\tabcolsep{1ex}
    \setlength{\extrarowheight}{0pt}
    \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} r L{\textwidth * \real{0.9}}}
}{
    \end{tabular*}
  \end{center}
}
% Define a line of cv information(skill)
% Usage: \cvskill{<type>}{<skillset>}
\newcommand*{\cvskill}[2]{
	\skilltypestyle{#1} & \skillsetstyle{#2} 
  \\
}

This is the code for the skills.tex file that I import as a section dir in resume.latex:

\cvsection{Skills}

\begin{cvskills}

\cvskill
{Languages:} % Category
{\small Go, Scala} % Skills

\cvskill
{Technologies:} % Category
{\small Kubernetes, AWS, Docker} % Skills

\end{cvskills}

Please help, it's urgent

**Comment by throwAway1023** [comment]
I don't want that indentation before Mobile dev, please let me know if the question is not clear

**Comment by Eyituoyo** [comment]
did you ever figure this out?

**Comment by posquit0** [comment]
Hi,
Thank you for using AwesomeCV. I haven't touched that project for a long time so I can't help.

Please post your issue with details on [Awesome-CV GitHub issues](https://github.com/posquit0/Awesome-CV/issues). Then, you can get help from people. 

This is a place to post personal questions. 😄

**Comment by yuvalnsn** [comment]
You need to add  **\raggedright** to the command.
In `awesome-cs.cls`:
_change -_ 
 ```
\newcommand*{\cvskill}[2]{%
 \honordatestyle{#4} & \honorpositionstyle{#1}, & \honortitlestyle{#2} & \honorlocationstyle{#3} \\
}
```
_to -_
```
\newcommand*{\cvskill}[2]{%
  \raggedright \honordatestyle{#4} & \honorpositionstyle{#1}, & \honortitlestyle{#2} & \honorlocationstyle{#3} \\
}
```
