### ISSUE TITLE
Awesome CV awesome-cv.cls Modification Question

### ISSUE THREAD

**Issue by njcleri** [posquit0/ama#6]
Hello Claud,

My name is Nikko Cleri, and I am a physics graduate student at the University of Connecticut in the US. I have been using your Awesome CV template for about a year now, and I absolutely love it. I think I have gotten to a point of being good enough with LaTex to start making some fine tuned modifications, but the one that I am having real troubles with is the font color of the \cvsection{} headers, where the default is to have the first three characters colored separately. I have been scouring the awesome-cv.cls file  for the last day hoping to find exactly where this is defined so I can tweak it. If you have any advice or direction I would greatly appreciate it. Thank you again for making such a great CV template publicly available.

Thank you,

Nikko Cleri

**Comment by DavideFauri** [comment]
Hello Nikko, I've recently forked this project and done such a modification, you can look it up here: https://github.com/DavideFauri/Awesome-CV/commit/1c13296edf7de1efecf0b99d2c268de3606d625f

**Comment by hank-w** [comment]
@DavideFauri Do you know how to reduce the space between sections subsections? I want to reduce the margins between Skills and the skills table. I also want to reduce the space between the Job title and job position, Thanks!

**Comment by DavideFauri** [comment]
Hi, sorry for the late answer.

> Do you know how to reduce the space between sections subsections?

What I usually do is open `awesome-cv.cls` and Ctrl+F for the command that I want to modify... In this case I see that, around line 580 (in my -custom- version of the file) the `\cvsubsection` command is defined:

```latex
\newcommand{\cvsubsection}[1]{%
  \vspace{\acvSectionContentTopSkip}
  \vspace{-3mm}
  \subsectionstyle{#1}
  \phantomsection
}
```

You just need to increase the amount of `\vspace` (negative numbers means a negative vertical space, i.e. it shifts stuff upwards) and that should do the trick.

> I also want to reduce the space between the Job title and job position, Thanks!

The same logic applies:
    1. find the command that you want to modify -> `\cventry`
    2. go to its definition in the `.cls` file -> line 605 (in my file)
    3. play around with the spacing until you get the result that you want
        3a. in some cases, spacing is handled by creating `tabular` environments. They have their own rules for vertical and horizontal spacing, but luckily stackoverflow is filled with answered questions for these issues.

Best of luck!

**Comment by Eyituoyo** [comment]
Hi @DavideFauri 

May I also ask a question How do you "enter" in LaTeX

**Comment by posquit0** [comment]
Hi,
Thank you for using AwesomeCV. I haven't touched that project for a long time so I can't help.

Please post your issue with details on [Awesome-CV GitHub issues](https://github.com/posquit0/Awesome-CV/issues). Then, you can get help from people. 

This is a place to post personal questions. 😄
